name: "Newt Add-on"
version: "1.2.0"
slug: "newt"
description: "Runs Newt inside Home Assistant OS"
arch:
  - amd64
  - armv7
  - armhf
  - aarch64
startup: system
boot: auto
host_network: true
privileged:
  - SYS_ADMIN
  - NET_ADMIN
  - DAC_READ_SEARCH
options:
  PANGOLIN_ENDPOINT: "https://dash.opland.net"
  NEWT_ID: "your_newt_id"
  NEWT_SECRET: "your_newt_secret"
schema:
  PANGOLIN_ENDPOINT: "str"
  NEWT_ID: "str"
  NEWT_SECRET: "str"
hassio_api: true
homeassistant_api: true
auth_api: true
hassio_role: "admin"