name: "Newt Add-on"
version: "1.1.3"
slug: "newt"
description: "Runs the Newt container inside Home Assistant using Supervisor API"
arch:
  - amd64
  - armv7
  - armhf
  - aarch64
startup: system
boot: auto
host_network: true
privileged:
  - SYS_ADMIN
  - NET_ADMIN
  - DAC_READ_SEARCH
options:
  PANGOLIN_ENDPOINT: "https://example.com"
  NEWT_ID: ""
  NEWT_SECRET: ""
schema:
  PANGOLIN_ENDPOINT: "str"
  NEWT_ID: "str"
  NEWT_SECRET: "str"
hassio_api: true
homeassistant_api: true
auth_api: true
hassio_role: "admin"
