name: "Newt Add-on"
version: "1.0.6"  # Incremented to force update
slug: "newt"
description: "Runs the Newt container inside Home Assistant using Supervisor API"
arch:
  - amd64
  - armv7
  - armhf
  - aarch64
startup: "system"
boot: "auto"
host_network: true
privileged: 
  - SYS_ADMIN
  - NET_ADMIN
options:
  PANGOLIN_ENDPOINT: "https://example.com"
  NEWT_ID: "your_newt_id"
  NEWT_SECRET: "your_newt_secret"
schema:
  PANGOLIN_ENDPOINT: "str?"
  NEWT_ID: "str?"
  NEWT_SECRET: "str?"
hassio_api: true
homeassistant_api: true
auth_api: true
hassio_role: "admin"