name: Sync to Forgejo

on:
  push:
    branches:
      - main

jobs:
  mirror:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout GitHub repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Henter hele repoet, ikke bare siste commit

      - name: Push to Forgejo
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

          git remote add forgejo https://Ferdinand99:${{ secrets.FORGEJO_TOKEN }}@git.opland.net/Ferdinand99/home-assistant-newt-addon.git
          git push forgejo main
